use_frameworks!

platform :ios, '10.0'

target 'KRPrinting_Example' do
  pod 'KRPrinting', :path => '../'

  target 'KRPrinting_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
